// C Header File
// Created 11/8/2002; 6:06:11 PM

#ifndef __DLL_EXPORTS__
#define __DLL_EXPORTS__

#define METROID_ID 0x13379009
#define MAJOR_VERSION 0
#define MINOR_VERSION 0

enum METGAME {
//	DLL_GET_STATE,
//	DLL_SET_STATE,

	GRAYSPRITECLIP8_OR,
	GRAYSPRITECLIP8_MASK,
	GRAYSPRITECLIP16_MASK,
	GRAYSPRITECLIP32_MASK,
	GRAYSPRITECLIPX8_MASK,
	GRAYSPRITECLIPX8_WMASK,
	GRAYSPRITECLIPVFLIPX8_MASK,
	RECT_OVERLAP,
	//RECT_DIAG_OVERLAP,
	TEST_COLLIDE_X8,

	//DLL_TILE_LIST,
	//DLL_TILE_LIST_CLIPPED,
	BG_SETUP,
	BG_RESET,
	BG_CLEANUP,
	BG_DRAW,
	DRAW_MAP0,
	DRAW_MAP1,
	GET_DATA,
	GET_PROP_DATA,
	SET_DATA,
	SET_PROP_DATA,

	BLOCK_SETUP,
	BLOCK_RESET,
	BLOCK_CLEANUP,
	BLOCK_CREATE,
	BLOCK_STRETCH_VERT,
	BLOCK_STRETCH_HORIZ,
	BLOCK_MOVE,
	BLOCK_DELETE,
	BLOCK_TEST,
	BLOCK_CHECK,

	ANIMATION_SETUP,
	ANIMATION_RESET,
	ANIMATION_CLEANUP,
	ANIMATION_CREATE,
	ANIMATION_DELETE,
	ANIMATION_PROCESS,
	ANIMATION_DRAW,

	//DLL_TILE_DATA,
	TILE_SETUP,
	TILE_CLEANUP,
	TILESET_LOAD,
	HOLE_RESET,
	HOLE_ENEMY_CHECK,
	HOLE_CREATE,
	HOLE_PROCESS,

	HIT_SLOPE_UP,
	HIT_SLOPE_DOWN,
	HIT_SOLID,
	ENTITY_INIT,
	ENTITY_SET_POS,
	ENTITY_CHECK_SIZE,
	ENTITY_SET_SIZE,
	ENTITY_SET_GRAVITY,
	ENTITY_RESET_SLOPE,
	ENTITY_GRAVITY_ROTATE_RIGHT,
	ENTITY_GRAVITY_ROTATE_LEFT,
	ENTITY_CHECK_DIRECTION,
	ENTITY_MOVE_INTERNAL,
	ENTITY_MOVE_SIMPLE,
	ENTITY_MOVE,
	ENTITY_DRAW,

	//DLL_WATER,
	ENVIRONMENT_SETUP,
	ENVIRONMENT_PROCESS,
	ENVIRONMENT_DRAW,
	
	PIPE_INIT,
	PIPE_RESET,
	PIPE_CLEANUP,
	PIPE_OPEN,
	PIPE_PROCESS,
	PIPE_DRAW,
};

enum METSYS {
	STRING_WIDTH,
	DRAW_STRING,
	DRAW_STRING_EX,
	MESSAGE,
	DRAW_BORDER,
	MENU_CREATE,
	MENU_ADD_CHOICE,
	MENU_PROCESS,
	TITLE_SCREEN,
};

enum DLL_IMPORTS {
	GFX_SETUP,
	GFX_CLEANUP,
	FLIPPING_OFF,
	FLIPPING_ON,
	CLEAR_BUFFER,
	UPDATE_SCREEN,
	PAUSE,
	DELAY,
	FILE_EXISTS,
	FILE_POINTER,
	ERROR,
	
	PLAYER_MOVE,

	SPRITEX8,
	GRAY_SPRITEX8,
	GRAY_SPRITEX8_MASK,
	
	DECOMPRESS,
	
	DLL_IMPORT_NUMBER,
};

#endif
